### ISSUE TITLE
Dataset link is empty，would you like to share it？

### ISSUE THREAD

**Issue by JieWu02** [less-and-less-bugs/Trust_TELLER#1]

**Comment by less-and-less-bugs** [comment]
Really? I can download the dataset from the link I shared. Could you give me some screenshots to check?

**Comment by JieWu02** [comment]
> Really? I can download the dataset from the link I shared. Could you give me some screenshots to check?

thanks for your response and kindness，this is what I see：
![image](https://github.com/less-and-less-bugs/Trust_TELLER/assets/83527625/2aeaef94-4757-4df6-971b-bb9fe71fc6bb)

**Comment by JieWu02** [comment]
> Really? I can download the dataset from the link I shared. Could you give me some screenshots to check?

I think it is because you set it into private, when I open the link, it require a CItyU address ,like follows:
![image](https://github.com/less-and-less-bugs/Trust_TELLER/assets/83527625/51142509-ae18-4d52-b950-8ebcbbe7e764)

**Comment by less-and-less-bugs** [comment]
https://portland-my.sharepoint.com/:u:/g/personal/liuhui3-c_my_cityu_edu_hk/EfApQlFP3PhFjUW4527STo0BALMdP16zs-HPMNgwQVFWsA?e=sTkux3

Can you download using this link?

**Comment by less-and-less-bugs** [comment]
<img width="458" alt="image" src="https://github.com/less-and-less-bugs/Trust_TELLER/assets/95093959/de1c9a53-ec30-4ad8-97ef-859a1b945fd3">
I am not sure but it has been shared.

**Comment by JieWu02** [comment]
> https://portland-my.sharepoint.com/:u:/g/personal/liuhui3-c_my_cityu_edu_hk/EfApQlFP3PhFjUW4527STo0BALMdP16zs-HPMNgwQVFWsA?e=sTkux3
> 
> Can you download using this link?

I am sorry, I am facing the same situation like previous link. I think we can share the dataset in another way, may be Baidu Disk, and others if you are convenient

**Comment by less-and-less-bugs** [comment]
I'm very sorry about that. If you like, please send me your email address and I will send it to you.

**Comment by JieWu02** [comment]
> I'm very sorry about that. If you like, please send me your email address and I will send it to you.

whu_wujie@163.com, thank you very much!

**Comment by less-and-less-bugs** [comment]
Hi, I have sent it to you. If you have any questions, please feel free to ask me!

**Comment by JieWu02** [comment]
> I'm very sorry about that. If you like, please send me your email address and I will send it to you.

Got it ! Wish your work a good result !

**Comment by JieWu02** [comment]
I'm from the mainland and lately some websites like arxiv and one drive really don't work. When I turn on **untraceable mode** of chrome, I can see the files. Next time someone encounter the same problem, you can refer to this solution.
